version: "3.9"

services:
  redis:
    image: redis:7
    container_name: sc_redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sc_worker
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    command: >
      uv run celery -A app.tasks worker --loglevel=INFO
